Feature/dry run reviewpad on reviewpad.yml change
reviewpad/action pull request #12
Opened 2022-07-24 06:08 UTC by zolamk

# Description

This PR changes the action so that if the `reviewpad.yml` file has been changed by a pull request, it will run Reviewpad in dry run mode using the `reviewpad.yml` file from the pull request.

# Related Issues
#10
reviewpad/reviewpad#158

2022-07-25 14:21 UTC, marcelosousa commented
Closes #10

2022-07-25 16:45 UTC, marcelosousa requested changes
Many thanks for this contribution 🙌 and sorry for the delay in the review! Left some comments in the diff!

2022-07-25 16:45 UTC, marcelosousa commented on agent/utils.go
> +package agent
I think this file should live in a different package called 'utils'.

2022-07-25 16:45 UTC, marcelosousa commented on agent/utils.go
> +
I don't think this empty line at the beginning of every function adds to the readability of the function. Is there a particular reason why you added this?

2022-07-25 16:45 UTC, marcelosousa commented on agent/utils.go
> +)
These could live in the `errors.go` in the utils package.

2022-07-25 16:45 UTC, marcelosousa commented on agent/runners.go
> +		if reviewPadFile, err = loadReviewPadFile(rawBaseFile); err != nil {
Please rename the occurrences of "Pad" to "pad" as in "reviewPadFile" -> "reviewpadFile".

2022-07-25 16:45 UTC, marcelosousa commented on agent/runners.go
> +	}
I think it could be easier to check if the reviewpad file is part of the diff no? 

You could use `files, err := utils.GetPullRequestFiles(ctx, client, env.RepoOwner, env.RepoName, env.PRNumber)`
from the reviewpad/reviewpad repository.

WDYT?

2022-07-25 16:45 UTC, marcelosousa commented on agent/runners.go
> +		if reviewPadFile, err = loadReviewPadFile(rawBaseFile); err != nil {
Not sure if there was a need to abstract the function `loadReviewpadFile` as it is quite simple.

2022-07-25 18:30 UTC, zolamk commented on agent/utils.go
> +
No reason, just force of habit.

2022-07-25 19:48 UTC, zolamk commented on agent/runners.go
> +	}
I agree, that's a much efficient solution to determine if the configuration file has changed.

2022-07-26 08:54 UTC, marcelosousa requested changes
Thanks for these changes. I've left a few more comments!

2022-07-26 08:54 UTC, marcelosousa commented on agent/runners.go
> +	files, err := reviewpad_utils.GetPullRequestFiles(ctx, client, repoOwner, repoName, *pullRequest.Number)
Missing check for err != nil.

2022-07-26 08:54 UTC, marcelosousa commented on agent/runners.go
> +	files, err := reviewpad_utils.GetPullRequestFiles(ctx, client, repoOwner, repoName, *pullRequest.Number)
I think that we should make this check a bit more robust in a separate function. Before doing this request we should check if the pull request doesn't change a huge number of files (which happens from time to time). If that is the case, your first initial solution could be more performant.

2022-07-26 08:54 UTC, marcelosousa commented on agent/runners.go
> +		err = runReviewpadPremium(ctx, env, client, clientGQL, collectorClient, pullRequest, eventPayload, reviewpadFile, dryRun)
Please add a //TODO comment because we'll have to do this change in the premium version.

2022-07-26 08:54 UTC, marcelosousa commented on utils/file.go
> +
Please remove this empty line.

2022-07-26 08:54 UTC, marcelosousa commented on utils/branch_test.go
> +
Please remove this empty line.

2022-07-26 12:58 UTC, zolamk commented on agent/runners.go
> +	files, err := reviewpad_utils.GetPullRequestFiles(ctx, client, repoOwner, repoName, *pullRequest.Number)
How many files is too many to do a linear check for file change? More than 50 or so?

2022-07-26 14:26 UTC, marcelosousa commented on agent/runners.go
> +	files, err := reviewpad_utils.GetPullRequestFiles(ctx, client, repoOwner, repoName, *pullRequest.Number)
Yes, I think 50 is good.

2022-07-26 14:30 UTC, marcelosousa requested changes
This is looking very good 🙌  Only one comment left!

2022-07-26 14:30 UTC, marcelosousa commented on utils/file.go
> +		}
This logic breaks in a pull request with more than 50 files where the reviewpad.yml is added. This is because there is no reviewpad file in the base branch and it will likely return an error in L23. We need to account for the case where the file might not exist in the branch.

2022-07-27 13:40 UTC, marcelosousa requested changes
While testing, I found a bug when retrieving the pull request files. I made some code suggestions.

2022-07-27 13:40 UTC, marcelosousa commented on utils/file.go
> +	branchRepoName := *pullRequest.Head.Repo.Name
AFAIK, the pull request always lives in the base repository.

```suggestion
	branchRepoOwner := *pullRequest.Base.Repo.Owner.Login
	branchRepoName := *pullRequest.Base.Repo.Name
```

2022-07-27 13:40 UTC, marcelosousa commented on utils/file.go
> +			if strings.Contains(err.Error(), "no file named") {
```suggestion
			if strings.HasPrefix(err.Error(), "no file named") {
```

2022-07-28 11:58 UTC, marcelosousa commented
Subsumed by https://github.com/reviewpad/action/pull/16

2022-07-28 11:58 UTC, closed without merging